### ISSUE TITLE
not enough arguments in call to client.ObtainCertificate

### ISSUE THREAD

**Issue by awkejiang** [minio/concert#15]
$ go get -v -u github.com/minio/concert
github.com/minio/concert (download)
github.com/minio/cli (download)
github.com/xenolf/lego (download)
github.com/miekg/dns (download)
Fetching https://golang.org/x/crypto/ocsp?go-get=1
Parsing meta tags from https://golang.org/x/crypto/ocsp?go-get=1 (status code 200)
get "golang.org/x/crypto/ocsp": found meta tag main.metaImport{Prefix:"golang.org/x/crypto", VCS:"git", RepoRoot:"https://go.googlesource.com/crypto"} at https://golang.org/x/crypto/ocsp?go-get=1
get "golang.org/x/crypto/ocsp": verifying non-authoritative meta tag
Fetching https://golang.org/x/crypto?go-get=1
Parsing meta tags from https://golang.org/x/crypto?go-get=1 (status code 200)
golang.org/x/crypto (download)
Fetching https://golang.org/x/net/publicsuffix?go-get=1
Parsing meta tags from https://golang.org/x/net/publicsuffix?go-get=1 (status code 200)
get "golang.org/x/net/publicsuffix": found meta tag main.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net/publicsuffix?go-get=1
get "golang.org/x/net/publicsuffix": verifying non-authoritative meta tag
Fetching https://golang.org/x/net?go-get=1
Parsing meta tags from https://golang.org/x/net?go-get=1 (status code 200)
golang.org/x/net (download)
Fetching https://gopkg.in/square/go-jose.v1?go-get=1
Parsing meta tags from https://gopkg.in/square/go-jose.v1?go-get=1 (status code 200)
get "gopkg.in/square/go-jose.v1": found meta tag main.metaImport{Prefix:"gopkg.in/square/go-jose.v1", VCS:"git", RepoRoot:"https://gopkg.in/square/go-jose.v1"} at https://gopkg.in/square/go-jose.v1?go-get=1
gopkg.in/square/go-jose.v1 (download)
Fetching https://gopkg.in/square/go-jose.v1/cipher?go-get=1
Parsing meta tags from https://gopkg.in/square/go-jose.v1/cipher?go-get=1 (status code 200)
get "gopkg.in/square/go-jose.v1/cipher": found meta tag main.metaImport{Prefix:"gopkg.in/square/go-jose.v1", VCS:"git", RepoRoot:"https://gopkg.in/square/go-jose.v1"} at https://gopkg.in/square/go-jose.v1/cipher?go-get=1
get "gopkg.in/square/go-jose.v1/cipher": verifying non-authoritative meta tag
Fetching https://gopkg.in/square/go-jose.v1?go-get=1
Parsing meta tags from https://gopkg.in/square/go-jose.v1?go-get=1 (status code 200)
Fetching https://gopkg.in/square/go-jose.v1/json?go-get=1
Parsing meta tags from https://gopkg.in/square/go-jose.v1/json?go-get=1 (status code 200)
get "gopkg.in/square/go-jose.v1/json": found meta tag main.metaImport{Prefix:"gopkg.in/square/go-jose.v1", VCS:"git", RepoRoot:"https://gopkg.in/square/go-jose.v1"} at https://gopkg.in/square/go-jose.v1/json?go-get=1
get "gopkg.in/square/go-jose.v1/json": verifying non-authoritative meta tag
github.com/minio/cli
github.com/miekg/dns
golang.org/x/crypto/ocsp
golang.org/x/net/publicsuffix
gopkg.in/square/go-jose.v1/cipher
gopkg.in/square/go-jose.v1/json
gopkg.in/square/go-jose.v1
github.com/xenolf/lego/acme
github.com/minio/concert
\# github.com/minio/concert
../Go/src/github.com/minio/concert/certs.go:127: not enough arguments in call to client.ObtainCertificate
../Go/src/github.com/minio/concert/certs.go:186: not enough arguments in call to client.RenewCertificate

**Comment by harshavardhana** [comment]
Can you use the released binaries instead - https://github.com/minio/concert/releases ? @awkejiang

**Comment by harshavardhana** [comment]
Project deprecated users should use [`certbot`](https://certbot.eff.org/) instead.  Closing.
