### ISSUE TITLE
concert renew error

### ISSUE THREAD

**Issue by exactt** [minio/concert#17]
Hi,

running Ubuntu 14.04 here. This is the first time I want to renew my certificate.

~/my-certs# concert renew --dir "." me@company.com

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4ddbf9]

goroutine 20 [running]:
panic(0x91a1c0, 0xc8200100e0)
	/root/bin/go/src/runtime/panic.go:464 +0x3e6
github.com/xenolf/lego/acme.(*Client).getChallenges.func1(0xc820152090, 0xc8202b86c0, 0xc8202b8660, 0xc820444980, 0xc)
	/root/go/src/github.com/xenolf/lego/acme/client.go:563 +0x5c9
created by github.com/xenolf/lego/acme.(*Client).getChallenges
	/root/go/src/github.com/xenolf/lego/acme/client.go:576 +0x17c
```

Any hints for me what is going wrong?

**Comment by harshavardhana** [comment]
> running Ubuntu 14.04 here. This is the first time I want to renew my certificate.
> 
> ~/my-certs# concert renew --dir "." me@company.com
> 
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal 0xb code=0x1 addr=0x0 pc=0x4ddbf9]
> 
> goroutine 20 [running]:
> panic(0x91a1c0, 0xc8200100e0)
> 	/root/bin/go/src/runtime/panic.go:464 +0x3e6
> github.com/xenolf/lego/acme.(*Client).getChallenges.func1(0xc820152090, 0xc8202b86c0, 0xc8202b8660, 0xc820444980, 0xc)
> 	/root/go/src/github.com/xenolf/lego/acme/client.go:563 +0x5c9
> created by github.com/xenolf/lego/acme.(*Client).getChallenges

This looks like a crash inside acme/client - the `me@company.com` is an invalid email id perhaps was never used during generating certs.

**Comment by harshavardhana** [comment]
Ah now i see upstream changed the way they save registration details, they require `accounts.json` you might have to regenerate your certs rather than renew. It should work fine after that.

**Comment by exactt** [comment]
Regenerating the certs worked. Renewing is still not working though...
