### ISSUE TITLE
add san-domains

### ISSUE THREAD

**Issue by secured** [minio/concert#21]
Let's Encrypt supports SAN domains. concert should give the user the ability to generate certs with multiple domains that are not subdomains.

**Comment by secured** [comment]
https://gist.github.com/secured/ee82f214e4d061958ed627887b50c20d

**Comment by harshavardhana** [comment]
Please send a proper PR @secured Thanks for the PR.

**Comment by secured** [comment]
#22

**Comment by harshavardhana** [comment]
Fixed by #22
