### ISSUE TITLE
Concert Error When Running 

### ISSUE THREAD

**Issue by BraydenGirard** [minio/concert#23]
If I run concert without sudo I get the following error: 

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x4c5a66]

If running concert with sudo as in the documentation I get:

sudo: concert: command not found

I have installed go and also installed and compiled concert as in the documentation.

**Comment by vadmeste** [comment]
@BraydenGirard, can you run concert this way:
`$ sudo $(which concert)` ?

**Comment by BraydenGirard** [comment]
Yes, interesting assuming it was not properly added to the path then.

**Comment by vadmeste** [comment]
We'll keep this open since it seems you found a bug.

**Comment by secured** [comment]
Same here while trying to renew

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0xe442c]

goroutine 13 [running]:
panic(0x40f160, 0x10822030)
        /usr/local/opt/go/libexec/src/runtime/panic.go:464 +0x330
github.com/xenolf/lego/acme.(*Client).getChallenges.func1(0x10b139f0, 0x10b23b00, 0x10b23ac0, 0x10b3dd60, 0x16)
        /Users/harsha/mygo/src/github.com/xenolf/lego/acme/client.go:408 +0xf8
created by github.com/xenolf/lego/acme.(*Client).getChallenges
        /Users/harsha/mygo/src/github.com/xenolf/lego/acme/client.go:421 +0x12c
```

**Comment by harshavardhana** [comment]
Project deprecated users should use [`certbot`](https://certbot.eff.org/) instead.  Closing.
