### ISSUE TITLE
Can't install concert on centos 7.3

### ISSUE THREAD

**Issue by chetankapoor** [minio/concert#24]
$ echo $GOPATH
/root/projects/src
$ echo $GOROOT
/usr/local/go
$ go get github.com/minio/concert
$ ll /usr/local/go/
total 144
drwxr-xr-x.  2 root root  4096 Aug 15  2016 api
-rw-r--r--.  1 root root 29041 Aug 15  2016 AUTHORS
drwxr-xr-x.  2 root root  4096 Aug 15  2016 bin
drwxr-xr-x.  4 root root  4096 Aug 15  2016 blog
-rw-r--r--.  1 root root  1168 Aug 15  2016 CONTRIBUTING.md
-rw-r--r--.  1 root root 40192 Aug 15  2016 CONTRIBUTORS
drwxr-xr-x.  8 root root  4096 Aug 15  2016 doc
-rw-r--r--.  1 root root  1150 Aug 15  2016 favicon.ico
drwxr-xr-x.  3 root root  4096 Aug 15  2016 lib
-rw-r--r--.  1 root root  1479 Aug 15  2016 LICENSE
drwxr-xr-x. 14 root root  4096 Aug 15  2016 misc
-rw-r--r--.  1 root root  1303 Aug 15  2016 PATENTS
drwxr-xr-x.  7 root root  4096 Aug 15  2016 pkg
-rw-r--r--.  1 root root  1638 Aug 15  2016 README.md
-rw-r--r--.  1 root root    26 Aug 15  2016 robots.txt
drwxr-xr-x. 45 root root  4096 Aug 15  2016 src
drwxr-xr-x. 18 root root 12288 Aug 15  2016 test
-rw-r--r--.  1 root root     5 Aug 15  2016 VERSION

I used the following link to install go 
https://www.digitalocean.com/community/tutorials/how-to-install-go-1-7-on-centos-7

**Comment by koolhead17** [comment]
@chetankapoor thanks for reporting. Let me test it on my end and get back to you. 😄

**Comment by koolhead17** [comment]
Also the error observed as mentioned on slack

```
# golang.org/x/crypto/ocsp
/root/projects/src/src/golang.org/x/crypto/ocsp/ocsp.go:201: undefined: elliptic.P224
```

**Comment by koolhead17** [comment]
@chetankapoor installation works as expected. 
Let me walk you through the steps i followed

1. Install golang by following http://docs.minio.io/docs/how-to-install-golang
```
  28  yum install git
   29  wget https://storage.googleapis.com/golang/go1.7.4.linux-amd64.tar.gz
   30  yum install wget
   31  wget https://storage.googleapis.com/golang/go1.7.4.linux-amd64.tar.gz
   32  tar -C ${HOME} -xzf go1.7.4.linux-amd64.tar.gz
   33  yum install nano
   34  nano .bashrc 
   35  source ~/.bashrc
```
Testing Go setup

```
# go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/work"
GORACE=""
GOROOT="/root/go"
GOTOOLDIR="/root/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```
# go version

```
go version go1.7.4 linux/amd64
```
2.  Installing concert  following http://docs.minio.io/docs/generate-let-s-encypt-certificate-using-concert-for-minio

```
[root@localhost ~]# concert --help
NAME:
  concert - Console certificate generation tool

USAGE:
  concert [global options] command [command options] [arguments...]

VERSION:
  0.0.3

AUTHOR:
  Minio, Inc.

COMMANDS:
  gen      Generate certificates (valid for 90 days).
  renew    Renew certificates (valid for 90 days).
  server   Run in server mode to automatically renew certificate, once in every 45 days.
  help, h  Shows a list of commands or help for one command

GLOBAL FLAGS:
  --help, -h     show help
  --version, -v  print the version

```
I have tested it on CetOS 7.3

```
# cat /etc/*elease
CentOS Linux release 7.3.1611 (Core) 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.3.1611 (Core) 
CentOS Linux release 7.3.1611 (Core) 
```

Please test it again from your side and close the issue after it works for you.

**Comment by chetankapoor** [comment]
@koolhead17 Now it works perfectly..
Thanks for the steps.. 👍
