### ISSUE TITLE
Add OCSP Stapling feature to the generated certificates

### ISSUE THREAD

**Issue by vadmeste** [minio/concert#26]
Firefox complains when it opens a secured TLS connection using certificates generated by concert. The error code shown by Firefox is MOZILLA_PKIX_ERROR_REQUIRED_TLS_FEATURE_MISSING error. Concert needs to ask for ocsp stabling feature.

**Comment by vadmeste** [comment]
concert already generates certificates with must staple feature. I already tested it with nginx. The problem is in the minio server.

In the other side, I think that it will be good if concert will have a flag to disable must staple in the generated certificate.

**Comment by harshavardhana** [comment]
> concert already generates certificates with must staple feature. I already tested it with nginx. The problem is in the minio server.
> 
> In the other side, I think that it will be good if concert will have a flag to disable must staple in the generated certificate.

It is not `must staple` feature it is `staple-ocsp` feature which is not present the lego/acme library.

**Comment by harshavardhana** [comment]
Project deprecated, closing this as won't fix.
