### ISSUE TITLE
multiple domains in one certificate

### ISSUE THREAD

**Issue by mxw39** [minio/concert#6]
Hi,

I find this tool very useful and thank you for building it. I was just thinking it would be nice to have the feature of requesting multiple domains for one certificate, such as putting `example.com` and `www.example.com` in one certificate.

Thanks,

**Comment by harshavardhana** [comment]
> Hi,
> 
> I find this tool very useful and thank you for building it. I was just thinking it would be nice to have the feature of requesting multiple domains for one certificate, such as putting example.com and www.example.com in one certificate.

Should be easy to do .. is this for having subdomain certificates?

**Comment by mxw39** [comment]
My preference is to give subdomains their respective certificates.

However, if it is the case that multiple apex domains lead to the same server, my opinion is that one certificate is better than multiple certificates.

**Comment by harshavardhana** [comment]
> My preference is to give subdomains their respective certificates.
> 
> However, if it is the case that multiple apex domains lead to the same server, my opinion is that one certificate is better than multiple certificates.

Yeah why not run the command itself for each domains or subdomains? again. right now the certs are produced for whichever domain you type. So it should work for that use case. 

The second one is supporting "Subject Alternate Names extension" certificate, which requires `concert` to take more domains but they all have to be part of the same CNAME suffix.

**Comment by mxw39** [comment]
> The second one is supporting "Subject Alternate Names extension" certificate, which requires concert to 
> take more domains but they all have to be part of the same CNAME suffix.

That is exactly what I meant. Sorry I didn't make myself clear at the beginning.

**Comment by harshavardhana** [comment]
> That is exactly what I meant. Sorry I didn't make myself clear at the beginning.

Would it be more useful to add 'domain.com' with 'www.domain.com' as default, since we wouldn't like to add support for more complex options on command line, let me think.

**Comment by mxw39** [comment]
Sure!

**Comment by harshavardhana** [comment]
> Sure!

Can you test and validate the patch? - https://github.com/minio/concert/pull/7

**Comment by harshavardhana** [comment]
@victorxw - `sudo ./concert gen --sub-domains www admin@example.com example.com` - here is how you can generate a single bundle.

**Comment by mxw39** [comment]
patch #7 tested and validated. Thanks!
