### ISSUE TITLE
How to run this side-by-side with a real http server?

### ISSUE THREAD

**Issue by nerab** [minio/concert#8]
The FAQ mentions that concert takes over ports 80 and 443 at some point in the flow. How is this supposed to work with a running web server that already uses these ports? Does it need to shut down in order to have concert to be able to do its thing?

**Comment by harshavardhana** [comment]
Yes that is correct. We tried using non standard ports but it did not seem to work reliably. But as of now yes.

**Comment by harshavardhana** [comment]
@nerab - Figuring out a way to do this. 

> TO use custom ports we need to make sure we proxy all the traffic to these ports.
> 
> HTTP Port:
> 
> All plaintext HTTP requests to port 80 which begin with a request path of /.well-known/acme-challenge/ for the HTTP challenge.
> TLS Port:
> 
> All TLS handshakes on port 443 for the TLS-SNI challenge.
> This traffic redirection is only needed as long as letsencrypt solves challenges. As soon as you have received your certificates you can deactivate the forwarding.

**Comment by nerab** [comment]
Ah, nice. 

Is there a way to formulate these rules as e.g. nginx proxy rules? Would make a nice drop-in config file for users with existing web servers like me ;-). Maybe also for Apache etc.

**Comment by harshavardhana** [comment]
Project deprecated users should use [`certbot`](https://certbot.eff.org/) instead.  Closing.
